
CREATE TABLE USERS (
 USERID           NUMERIC(4) NOT NULL,
 USERNAME         CHAR(16),
 PASSWORD         CHAR(16),
 FULLNAME         CHAR(60),
 EMAIL            CHAR(40),
 CONSTRAINT USERS_PRIMARY_KEY PRIMARY KEY (USERID));
 
 CREATE TABLE PLACES (
 PID             NUMERIC(4) NOT NULL,
 PNAME           NUMERIC(4),
 PDESCRIPTION    CHAR(200),
 PTYPE           CHAR(20),
 CONSTRAINT PLACES_PRIMARY_KEY PRIMARY KEY (PID));
 
 CREATE TABLE LOCATION (
 LID             NUMERIC(4) NOT NULL,
 PID             NUMERIC(4),
 LATITUDE        DOUBLE,
 LONGITUDE       DOUBLE,
 CONSTRAINT LOCATION_PRIMARY_KEY PRIMARY KEY (LID),
 CONSTRAINT LOCATION_FOREIGN_KEY FOREIGN KEY (PID) REFERENCES PLACES (PID));
 
 CREATE TABLE RATING (
 RID             NUMERIC(4) NOT NULL,
 PID             NUMERIC(4),
 STARS           INT(1),
 CONSTRAINT RATING_PRIMARY_KEY PRIMARY KEY (RID),
 CONSTRAINT RATING_FOREIGN_KEY FOREIGN KEY (PID) REFERENCES PLACES (PID));
 
 CREATE TABLE PICTURE (
 PICID            NUMERIC(4) NOT NULL,
 PLID             NUMERIC(4),
 LINK             CHAR(200),
 CONSTRAINT PICTURE_PRIMARY_KEY PRIMARY KEY (PICID),
 CONSTRAINT PICTURE_FOREIGN_KEY FOREIGN KEY (PLID) REFERENCES PLACES (PID));
 
 